# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Fl3-z4UTm1u6Wt34QjUeuI_CNvIox6L
"""

!pip install diffusers transformers accelerate safetensors gradio --quiet

import gradio as gr
import random
import torch
from diffusers import StableDiffusionPipeline
from PIL import Image

# ---------------- MODEL (GPU if available) ----------------
device = "cuda" if torch.cuda.is_available() else "cpu"
pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16 if device=="cuda" else torch.float32
).to(device)

# ---------------- DATA ----------------
OUTFITS = {
    "Male": {
        "Casual": ["Oversized t-shirt with cargo pants"],
        "Formal": ["Blazer with tailored trousers"],
        "Party": ["Black shirt with slim-fit jeans"]
    },
    "Female": {
        "Casual": ["Crop top with mom jeans"],
        "Formal": ["Elegant kurti with palazzo"],
        "Party": ["Sequin top with high-waist skirt"]
    }
}

TRENDS = [
    "Monochrome outfits are trending 🔥",
    "Earthy tones boost confidence 🌿",
    "Layering enhances elegance ✨",
    "Oversized fits dominate Gen-Z 😎"
]

SHOPPING_LINKS = [
    "https://www.myntra.com",
    "https://www.ajio.com",
    "https://www.amazon.in/fashion",
    "https://www.flipkart.com/fashion"
]

history = []

# ---------------- IMAGE GENERATOR ----------------
def generate_image(prompt):
    prompt = f"animated fashion model, faceless, studio lighting, {prompt}"
    with torch.autocast(device):
        return pipe(prompt, guidance_scale=7.5).images[0]

# ---------------- MAIN AI ----------------
def fashion_ai(desc, gender, occasion, ref_img):
    outfit = random.choice(OUTFITS[gender][occasion])
    trend = random.choice(TRENDS)
    confidence = random.randint(82, 96)

    img1 = generate_image(outfit)

    links = "\n".join([f"- {l}" for l in SHOPPING_LINKS])

    result = f"""
### 👗 AI Fashion Recommendation

**Style Need:** {desc}
**Gender:** {gender}
**Occasion:** {occasion}

✨ **Suggested Outfit:**
{outfit}

📈 **Trend Insight:**
{trend}

💯 **Trend Confidence:**
{confidence}%

🛒 **Shopping Links:**
{links}
"""

    history.append(outfit)
    if len(history) > 5:
        history.pop(0)

    return result, img1, "\n".join(history)

# ---------------- CHATBOT ----------------
def chatbot(msg):
    tips = [
        "Accessories elevate simple outfits.",
        "Neutral footwear balances bold styles.",
        "Layering increases confidence.",
        "Earth tones work universally.",
        "Minimal accessories look classy."
    ]
    return random.choice(tips)

# ---------------- LOGIN / SIGNUP ----------------
def login(u, p):
    if u and p:
        return gr.update(visible=False), gr.update(visible=True)
    return gr.update(visible=True), gr.update(visible=False)

def signup(u, p):
    if u and p:
        return gr.update(visible=False), gr.update(visible=True)
    return gr.update(visible=True), gr.update(visible=False)

# ---------------- UI ----------------
css = """
body, .gradio-container { background:#FFF3E0; }
.nav { display:flex; justify-content:flex-end; gap:15px; font-size:14px; }
.nav-btn { background:none; border:none; font-size:14px; font-weight:bold; color:#333; cursor:pointer; }
.header { background:#E6A73C; padding:45px; border-radius:20px; text-align:center; }
.card { background:#FFF8EC; padding:25px; border-radius:20px; margin-top:20px; }
.footer { background:#8B5E34; color:white; padding:20px; border-radius:20px; margin-top:25px; }
"""

with gr.Blocks(css=css, title="Styling AI") as app:

    login_page = gr.Column(visible=True)
    main_page = gr.Column(visible=False)

    # ---------------- LOGIN PAGE ----------------
    with login_page:
        gr.Markdown("## 🔐 Login / Sign Up")
        u = gr.Textbox(label="Username")
        p = gr.Textbox(label="Password", type="password")
        with gr.Row():
            gr.Button("Login").click(login, [u, p], [login_page, main_page])
            gr.Button("Sign Up").click(signup, [u, p], [login_page, main_page])

    # ---------------- MAIN PAGE ----------------
    with main_page:

        with gr.Row(elem_classes="nav"):
            home_btn = gr.Button("Home", elem_classes="nav-btn")
            about_btn = gr.Button("About", elem_classes="nav-btn")

        # ---------- HOME ----------
        home_section = gr.Column(visible=True)
        with home_section:
            gr.HTML("""
            <div class="header">
            <h1>Welcome to Styling AI 👗</h1>
            <p>Your personal AI fashion assistant. Get outfit suggestions, trend insights, and shopping links instantly!</p>
            </div>
            """)

            # Use local images for reliability
            local_paths = ["men.jpg", "women.jpg", "teen.jpg"]
            with gr.Row():
                for path in local_paths:
                    try:
                        img = Image.open(path).convert("RGB")
                        gr.Image(value=img, interactive=False, type="pil")
                    except Exception as e:
                        print(f"Failed to load image from {path}: {e}")

            # Try It button
            try_btn = gr.Button("✨ Try It")

        # ---------- ABOUT ----------
        about_section = gr.Column(visible=False)
        with about_section:
            gr.HTML("""
            <div class="card">
            <h2>About Styling AI</h2>
            <p>Styling AI is an AI-powered fashion recommendation system designed to provide personalized outfit suggestions for any occasion. It leverages the latest AI models to generate realistic fashion images and trend insights.</p>
            <p>Whether you're looking for casual, formal, or party outfits, Styling AI helps you make confident fashion choices!</p>
            </div>
            """)

        # ---------- RECOMMENDATION FORM ----------
        rec_section = gr.Column(visible=False)
        with rec_section, gr.Column(elem_classes="card"):
            desc = gr.Textbox(label="Describe your fashion need")
            gender = gr.Dropdown(["Male", "Female"], label="Gender")
            occasion = gr.Dropdown(["Casual", "Formal", "Party"], label="Occasion")
            ref = gr.Image(label="Upload Reference Image", type="pil")

            btn = gr.Button("✨ Generate Recommendation")
            out = gr.Markdown()
            img1_out = gr.Image()
            history_box = gr.Textbox(label="🕘 Previous Outfit Suggestions")

            btn.click(
                fashion_ai,
                [desc, gender, occasion, ref],
                [out, img1_out, history_box],
                show_progress=True
            )

        # ---------- CHATBOT ----------
        with gr.Column(elem_classes="card"):
            gr.Markdown("### 💬 AI Fashion Chatbot")
            q = gr.Textbox()
            a = gr.Textbox()
            q.submit(chatbot, q, a)

        # ---------- FOOTER ----------
        gr.HTML("""
        <div class="footer">
        <p>📍 Bengaluru, India</p>
        <p>📞 +91 98765 43210</p>
        <p>📧 support@stylingai.com</p>
        </div>
        """)

        # ---------- BUTTON LOGIC ----------
        def show_about():
            return gr.update(visible=False), gr.update(visible=True), gr.update(visible=False)

        def show_home():
            return gr.update(visible=True), gr.update(visible=False), gr.update(visible=False)

        def show_rec():
            return gr.update(visible=False), gr.update(visible=False), gr.update(visible=True)

        about_btn.click(show_about, [], [home_section, about_section, rec_section])
        home_btn.click(show_home, [], [home_section, about_section, rec_section])
        try_btn.click(show_rec, [], [home_section, about_section, rec_section])

# Launch app
app.launch(share=True)













